### ISSUE TITLE
Inquiry Regarding Dataset Source in Your GitHub Repository

### ISSUE THREAD

**Issue by miracle20010316** [davidycliao/taiwan-hatespeech-detection#1]
Sorry to bother you. I am writing to express my appreciation for your work on the  project. Your efforts have  provided valuable resources to the community.
I am particularly interested in the dataset mentioned in the README. Could you kindly tell me if this dataset was publicly available in the referenced paper, or did you obtain it directly from the paper's authors? This will greatly aid in my ongoing research.
Thanks again! :)

**Comment by davidycliao** [comment]
Hi @miracle20010316 could you email me at [davidycliao@gmail.com](mailto:davidycliao@gmail.com) and I am happy to forward your email to get the permission of the data author (the author of the paper) because I am not the original owner of the author's data. I also had to write to the publication to request the data, which is why I didn't upload the data I trained with.

**Comment by miracle20010316** [comment]
Thank you for your response. I have already sent an email to your inbox. Please check it at your earliest convenience.
